/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllPic: typeof import('./../components/business/AllPic.vue')['default']
    AppIcon: typeof import('./../components/common/AppIcon/AppIcon.vue')['default']
    BlockTitle: typeof import('./../components/common/BlockTitle.vue')['default']
    CheckTest: typeof import('./../components/common/CheckTest.vue')['default']
    DownloadProgress: typeof import('./../components/common/DownloadProgress.vue')['default']
    Empty: typeof import('./../components/common/Empty.vue')['default']
    FullDate: typeof import('./../components/common/FullDate/FullDate.vue')['default']
    ListMore: typeof import('./../components/common/ListMore.vue')['default']
    Loading: typeof import('./../components/common/Loading/Loading.vue')['default']
    PageNavBar: typeof import('./../components/common/PageNavBar.vue')['default']
    PagePopup: typeof import('./../components/common/PagePopup.vue')['default']
    PageRadio: typeof import('./../components/common/PageRadio.vue')['default']
    PageTag: typeof import('./../components/common/PageTag.vue')['default']
    PageTagSelecter: typeof import('./../components/common/PageTagSelecter.vue')['default']
    PageWatchFileList: typeof import('./../components/common/PageWatchFileList.vue')['default']
    Pagination: typeof import('./../components/common/Pagination.vue')['default']
    Pic: typeof import('./../components/common/Pic.vue')['default']
    PicSwiper: typeof import('./../components/business/PicSwiper.vue')['default']
    Tabbar: typeof import('./../components/Tabbar.vue')['default']
  }
}
